spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vaultpay_dev
    username: vaultpay
    password: vaultpay

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.vaultpay: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
